/**
 * app/src/lib/ens.ts
 *
 * Real ENSv2 minting for `<handle>.aval.eth` on Ethereum Sepolia (chainId 11155111) — a
 * DIFFERENT chain from AvalRegistry (World Chain Sepolia, 4801). docs/04-ens.md §7: "a member =
 * a PermissionedRegistry they own" — in this design the name is not a label attached to an
 * account, the name *is* the record.
 *
 * Every address and ABI shape here is taken from `deployments/ens-sepolia.json`, generated by
 * live, independently cross-checked reads/writes against the deployed contracts (Sourcify
 * exact_match on the .eth registry and the resolver; functional confirmation on the aval.eth
 * registry clone) — not guessed. `verify_ens_reads.mjs` (repo root, run once during this task)
 * re-confirmed every read used here against the live chain before this file was written.
 *
 * `DEPLOYER_PRIVATE_KEY` (== `PRIVATE_KEY` in this deployment's `.env` — confirmed by deriving its
 * address and comparing to the documented deployer, `0x69827C0F...9050`) holds `ALL_ROLES` on the
 * aval.eth registry clone, so it can `register()` new subnames. Server-only: this key must never
 * reach the client bundle.
 */

import "server-only";

import { createPublicClient, createWalletClient, http, namehash, type Address, type Hex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { sepolia } from "viem/chains";

export class EnsConfigError extends Error {}

const AVAL_ETH_REGISTRY: Address = "0xb8C3d3AD86b0b66CE5401c81e9c4a037DF69eF33"; // aval.eth's own PermissionedRegistry clone
const AVAL_ETH_RESOLVER: Address = "0x211D6CC339C7C6E4B4448c04cD034E363d9994d3"; // PermissionedResolver clone, wired to every aval.eth subname minted here
const DEPLOYER_ADDRESS: Address = "0x69827C0FEF274C63Ac4806106F2BA544E6129050";

/** `RegistryRolesLib`'s 64-slot nybble-packed roles bitmap, every nybble set — the exact value
 *  independently read back from `avalRegistry.roles(ROOT_RESOURCE=0, deployer)` on chain
 *  (deployments/ens-sepolia.json `avalEth.verifiedBy`), not a guess at what "all roles" means. */
const ALL_ROLES = 0x1111111111111111111111111111111111111111111111111111111111111111n;
const ROOT_RESOURCE = 0n;

const REGISTRY_ABI = [
  {
    type: "function",
    name: "register",
    stateMutability: "nonpayable",
    inputs: [
      { name: "label", type: "string" },
      { name: "owner", type: "address" },
      { name: "registry", type: "address" },
      { name: "resolver", type: "address" },
      { name: "roleBitmap", type: "uint256" },
      { name: "expiry", type: "uint64" },
    ],
    outputs: [{ name: "tokenId", type: "uint256" }],
  },
  {
    type: "function",
    name: "findOwner",
    stateMutability: "view",
    inputs: [{ name: "label", type: "string" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "getResolver",
    stateMutability: "view",
    inputs: [{ name: "label", type: "string" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "findExpiry",
    stateMutability: "view",
    inputs: [{ name: "label", type: "string" }],
    outputs: [{ name: "", type: "uint64" }],
  },
] as const;

const RESOLVER_ABI = [
  {
    type: "function",
    name: "setAddr",
    stateMutability: "nonpayable",
    inputs: [
      { name: "node", type: "bytes32" },
      { name: "a", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addr",
    stateMutability: "view",
    inputs: [{ name: "node", type: "bytes32" }],
    outputs: [{ name: "", type: "address" }],
  },
] as const;

function getDeployerAccount() {
  const key = process.env.DEPLOYER_PRIVATE_KEY ?? process.env.PRIVATE_KEY;
  if (!key) {
    throw new EnsConfigError("DEPLOYER_PRIVATE_KEY (or PRIVATE_KEY) is not set — cannot mint ENS subnames.");
  }
  const account = privateKeyToAccount(key as Hex);
  if (account.address.toLowerCase() !== DEPLOYER_ADDRESS.toLowerCase()) {
    throw new EnsConfigError(
      `Configured deployer key derives to ${account.address}, not the expected aval.eth registry owner ${DEPLOYER_ADDRESS}. Refusing to mint with an unverified key.`,
    );
  }
  return account;
}

function getRpcUrl(): string {
  const url = process.env.ETH_SEPOLIA_RPC;
  if (!url) throw new EnsConfigError("ETH_SEPOLIA_RPC is not set — cannot reach Ethereum Sepolia for ENS.");
  return url;
}

let cachedPublicClient: ReturnType<typeof createPublicClient> | null = null;
function getPublicClient() {
  if (!cachedPublicClient) {
    cachedPublicClient = createPublicClient({ chain: sepolia, transport: http(getRpcUrl()) });
  }
  return cachedPublicClient;
}

function getWalletClient() {
  return createWalletClient({ account: getDeployerAccount(), chain: sepolia, transport: http(getRpcUrl()) });
}

/** `findOwner(label) == address(0)` — the live, on-chain availability check (not a cache, not a
 *  guess). Same registry `getSubregistry` docs/04-ens.md §7.1 describes minting into. */
export async function isEnsLabelAvailable(label: string): Promise<boolean> {
  const owner = await getPublicClient().readContract({
    address: AVAL_ETH_REGISTRY,
    abi: REGISTRY_ABI,
    functionName: "findOwner",
    args: [label],
  });
  return owner === "0x0000000000000000000000000000000000000000";
}

/** Reads back what `<label>.aval.eth` actually resolves to right now — used both by the mint
 *  route (to confirm the write really took, not just that the tx didn't revert) and by
 *  `/api/ens/resolve` for independent verification. */
export async function resolveEnsLabel(label: string): Promise<Address | null> {
  const addr = await getPublicClient().readContract({
    address: AVAL_ETH_RESOLVER,
    abi: RESOLVER_ABI,
    functionName: "addr",
    args: [namehash(`${label}.aval.eth`)],
  });
  return addr === "0x0000000000000000000000000000000000000000" ? null : addr;
}

export interface MintResult {
  /** `null` when this call skipped `register()` because a prior attempt already completed it
   *  (resumed a partial mint) — an honest report of what THIS call actually did on chain. */
  registerTxHash: Hex | null;
  setAddrTxHash: Hex | null;
  resolvedAddress: Address | null;
  /** True when both steps were already done before this call ran (idempotent replay). */
  alreadyComplete: boolean;
}

const ZERO_ADDRESS: Address = "0x0000000000000000000000000000000000000000";

/**
 * Mints `<label>.aval.eth` and points it at `targetAddress` — the proven sequence in
 * `deployments/ens-sepolia.json`:
 *   1. `register(label, owner=deployer, registry=0x0, resolver=avalResolver, ALL_ROLES, expiry)`
 *      on the aval.eth registry clone (mirrors how `carol` was minted: the deployer keeps
 *      administrative ownership of the registry entry, consistent across every mint this app
 *      performs, rather than handing a brand-new wallet role bits on a chain it may not even
 *      hold ETH on).
 *   2. `setAddr(namehash(label + ".aval.eth"), targetAddress)` on the resolver — this is the step
 *      that actually makes the name resolve to a human. "The transaction succeeded" and "the name
 *      resolves" are different claims; only a live `addr()` readback after both writes land is
 *      trusted here, never assumed from a receipt.
 *
 * Idempotent and resumable, checked against live chain state (not a local flag) on every call:
 *  - label unregistered            -> register() + setAddr()
 *  - label registered, addr unset/wrong (an earlier `setAddr` failed) -> setAddr() only
 *  - label registered, addr already correct -> no writes, `alreadyComplete: true`
 * This is what makes "retry that doesn't re-enroll" (and doesn't double-register) possible
 * without a database: `register()` on an already-owned label reverts, so re-running it is never
 * silently attempted once ownership exists.
 */
export async function mintEnsSubname(label: string, targetAddress: Address): Promise<MintResult> {
  const wallet = getWalletClient();
  const publicClient = getPublicClient();

  const owner = await publicClient.readContract({ address: AVAL_ETH_REGISTRY, abi: REGISTRY_ABI, functionName: "findOwner", args: [label] });
  const alreadyRegistered = owner !== ZERO_ADDRESS;

  let registerTxHash: Hex | null = null;
  if (!alreadyRegistered) {
    const expiry = BigInt(Math.floor(Date.now() / 1000) + 365 * 24 * 60 * 60); // 1 year, matching the carol precedent
    registerTxHash = await wallet.writeContract({
      address: AVAL_ETH_REGISTRY,
      abi: REGISTRY_ABI,
      functionName: "register",
      args: [label, DEPLOYER_ADDRESS, ZERO_ADDRESS, AVAL_ETH_RESOLVER, ALL_ROLES, expiry],
    });
    const receipt = await publicClient.waitForTransactionReceipt({ hash: registerTxHash });
    if (receipt.status !== "success") {
      throw new Error(`register("${label}") reverted on Ethereum Sepolia: ${registerTxHash}`);
    }
  }

  const currentResolved = await resolveEnsLabel(label);
  if (currentResolved && currentResolved.toLowerCase() === targetAddress.toLowerCase()) {
    return { registerTxHash, setAddrTxHash: null, resolvedAddress: currentResolved, alreadyComplete: registerTxHash === null };
  }

  const setAddrTxHash = await wallet.writeContract({
    address: AVAL_ETH_RESOLVER,
    abi: RESOLVER_ABI,
    functionName: "setAddr",
    args: [namehash(`${label}.aval.eth`), targetAddress],
  });
  const setAddrReceipt = await publicClient.waitForTransactionReceipt({ hash: setAddrTxHash });
  if (setAddrReceipt.status !== "success") {
    // The name is minted (register succeeded, here or in a prior attempt) but doesn't resolve
    // yet — an honest partial state, not silently swallowed.
    throw new EnsMintPartialError(label, registerTxHash, setAddrTxHash);
  }

  const resolvedAddress = await resolveEnsLabel(label);
  return { registerTxHash, setAddrTxHash, resolvedAddress, alreadyComplete: false };
}

/** Thrown when `register()` succeeded but `setAddr()` reverted — the name exists but resolves to
 *  nothing. The caller is enrolled and their name is reserved; only the pointer write failed, and
 *  retrying should redo `setAddr` only, never `register` again (it would revert — already taken). */
export class EnsMintPartialError extends Error {
  label: string;
  registerTxHash: Hex | null;
  setAddrTxHash: Hex;
  constructor(label: string, registerTxHash: Hex | null, setAddrTxHash: Hex) {
    super(`"${label}.aval.eth" was minted but the address record failed to write.`);
    this.name = "EnsMintPartialError";
    this.label = label;
    this.registerTxHash = registerTxHash;
    this.setAddrTxHash = setAddrTxHash;
  }
}
